import type { Shop } from "./types";

// 店名・エリア・最寄駅・ジャンルなどの事実情報はWeb検索で収集した公開情報を元にしている。
// レビュー文・口コミ文・写真・他サイトの紹介文はコピーしておらず、コメント類（whyThisShop /
// keioNotes / tasteNotes / beginnerNotes / rulesNotes / studentBudgetNote / recommendedFor）は
// すべて編集部の言葉で短くまとめたオリジナル原稿。
// 価格は変動するため全店 priceConfidence: "approximate"（目安）とし、写真は未許諾のため imageUrl は
// 未設定。許諾済み写真が用意でき次第 imageUrl に入れれば各UIにそのまま反映される。
// 営業時間・徒歩分数・サービス内容も変わりうるため、訪問前に各店の最新情報を確認すること。

function mapsUrl(query: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

export const SHOPS: Shop[] = [
  // ===== 日吉 =====
  {
    id: "hiyoshi-musashiya",
    name: "武蔵家 日吉店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["日吉の家系激戦区", "学生の定番"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["after_class", "hearty", "no_fail"],
    budgetMin: 800,
    budgetMax: 1100,
    signatureOrderName: "ラーメン＋ライス",
    signatureOrderPrice: 950,
    studentBudgetNote: "ライスが進む濃いめスープ。この値段でしっかり満腹になれる。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 5,
    lightness: 1,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 5,
    nearness: 5,
    accessNote: "日吉駅から徒歩3分前後。キャンパスからも近く授業後に直行できる。",
    whyThisShop: "日吉で家系の王道といえばここ。迷ったらまず候補に入れたい一杯。",
    recommendedMenu: "ラーメン（ライス付き）",
    tasteNotes: "豚骨醤油の濃厚スープに、もっちりした中太麺を合わせる王道家系。",
    atmosphereNotes: "カウンター中心で回転が早く、ひとりでも気兼ねなく座れる。",
    beginnerNotes: "麺の硬さ・脂・味の濃さを聞かれるが、わからなければ「普通」で大丈夫。",
    rulesNotes: "卓上のニンニクや生姜で味変できる。ライスは家系の濃いスープとの相性が良い。",
    keioNotes: "日吉駅・キャンパスのどちらからも近く、授業終わりや空きコマの定番。",
    recommendedFor: ["授業終わりにがっつり食べたい人", "家系の基本を知りたい人"],
    googleMapsUrl: mapsUrl("武蔵家 日吉店"),
  },
  {
    id: "hiyoshi-ramendon",
    name: "ラーメンどん",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["日吉の二郎系インスパイア", "野菜マシ無料"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty", "after_club"],
    budgetMin: 750,
    budgetMax: 1000,
    signatureOrderName: "小ラーメン",
    signatureOrderPrice: 900,
    studentBudgetNote: "野菜・脂・にんにくが無料で増やせる。空腹で行けば満足度が高い。",
    priceConfidence: "approximate",
    visualTone: "jiro",
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 2,
    soloFriendly: 3,
    friendFriendly: 3,
    queueLevel: 4,
    speedLevel: 2,
    lateNight: false,
    keioStudentScore: 4,
    nearness: 5,
    accessNote: "日吉駅から徒歩1分。昼どきは行列ができることもある。",
    whyThisShop: "とにかく量を食べたい日に。日吉の二郎系インスパイアの代表格。",
    recommendedMenu: "小ラーメン（野菜マシ）",
    tasteNotes: "豚骨醤油の濃厚スープに極太麺、山盛りの野菜とアブラ。",
    atmosphereNotes: "学生の利用が多く、ボリューム狙いの客で賑わう。",
    beginnerNotes: "初めてなら「小」で十分な量。にんにくの有無は提供前に聞かれる。",
    rulesNotes: "野菜・脂・にんにくは無料で増量できる。最初は控えめが無難。",
    keioNotes: "日吉駅すぐで、サークル後や腹を空かせた日にがっつり食べたい時の定番。",
    recommendedFor: ["量を食べたい人", "二郎系に挑戦したい人"],
    googleMapsUrl: mapsUrl("ラーメンどん 日吉"),
  },
  {
    id: "hiyoshi-kokoro",
    name: "麺屋こころ 日吉店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["台湾まぜそばの行列店", "学生サービスあり"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["まぜそば"],
    sceneTags: ["with_friends", "after_class", "hearty"],
    budgetMin: 850,
    budgetMax: 1150,
    signatureOrderName: "台湾まぜそば",
    signatureOrderPrice: 950,
    studentBudgetNote: "学生向けに大盛・トッピング無料のサービスがあり、量で得しやすい。",
    priceConfidence: "approximate",
    visualTone: "mazesoba",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 3,
    friendFriendly: 5,
    queueLevel: 4,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 4,
    nearness: 5,
    accessNote: "日吉駅から徒歩1分。台湾まぜそばの人気店で行列ができることも。",
    whyThisShop: "日吉で行列を作る台湾まぜそば。混ぜて、追い飯まで楽しめる一杯。",
    recommendedMenu: "台湾まぜそば（追い飯付き）",
    tasteNotes: "甘辛い挽き肉・魚粉・ニラ・卵黄を極太麺に絡める台湾まぜそば。",
    atmosphereNotes: "学生客が多く活気がある。回転は比較的早い。",
    beginnerNotes: "提供されたらまず全体をよく混ぜる。最後はタレに追い飯を入れて〆る。",
    rulesNotes: "学生証提示で大盛やトッピングが無料になることがある。会計前に確認を。",
    keioNotes: "日吉駅すぐで、友達とがっつり・ワイワイ食べたい時に向くまぜそばの定番。",
    recommendedFor: ["まぜそばが好きな人", "友達とがっつり食べたい人"],
    googleMapsUrl: mapsUrl("麺屋こころ 日吉店"),
  },
  {
    id: "hiyoshi-hiyoshiya",
    name: "ひよし家",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["日吉では珍しいあっさり系"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["淡麗", "醤油"],
    sceneTags: ["gap_time", "solo", "no_fail"],
    budgetMin: 800,
    budgetMax: 1000,
    signatureOrderName: "醤油らーめん",
    signatureOrderPrice: 850,
    studentBudgetNote: "あっさり系をワンコイン＋αで。重い系に疲れた日にちょうどいい。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 2,
    lightness: 4,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 4,
    nearness: 5,
    accessNote: "日吉駅から徒歩3分前後。キャンパスからも近い。",
    whyThisShop: "家系・二郎が並ぶ日吉で、数少ないあっさり系の逃げ場。",
    recommendedMenu: "醤油らーめん",
    tasteNotes: "魚介を中心に、化調に頼らずだしを引いた透明感のあるスープ。",
    atmosphereNotes: "こぢんまりとした店内で、ひとりでも自然に過ごせる落ち着き。",
    beginnerNotes: "メニューがシンプルで、券売機を見れば迷わず選べる。",
    rulesNotes: "特別なルールはなし。トッピングは券売機の表示通りに選べばよい。",
    keioNotes: "毎日でも食べやすい軽さで、空きコマの一人飯にちょうどいい。",
    recommendedFor: ["あっさり系が好きな人", "重い系に疲れた日"],
    googleMapsUrl: mapsUrl("ひよし家 日吉駅"),
  },
  {
    id: "hiyoshi-taishoken",
    name: "日吉 大勝軒",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["永福町系の流れ", "麺量たっぷり"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["醤油", "淡麗"],
    sceneTags: ["solo", "gap_time", "hearty"],
    budgetMin: 850,
    budgetMax: 1150,
    signatureOrderName: "中華麺",
    signatureOrderPrice: 1000,
    studentBudgetNote: "一杯で麺量がたっぷり。あっさり寄りでも腹を満たせるのが強み。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 3,
    lightness: 3,
    volume: 5,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 3,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "日吉駅から徒歩1分前後。",
    whyThisShop: "煮干しと香味油の効いた、永福町系の流れをくむ特大の中華そば。",
    recommendedMenu: "中華麺",
    tasteNotes: "煮干しと香味油が効いた清湯スープに、見た目以上にたっぷりの麺。",
    atmosphereNotes: "町中華寄りの落ち着いた雰囲気で、一人でも入りやすい。",
    beginnerNotes: "麺量が多いので、少なめにしたい時は注文時に伝えると安心。",
    rulesNotes: "量が多めなのが特徴。食べきれるか不安なら麺少なめを相談できることが多い。",
    keioNotes: "日吉駅すぐで、あっさり寄りでもしっかり量が欲しい時の選択肢。",
    recommendedFor: ["煮干し系が好きな人", "重すぎず量は欲しい人"],
    googleMapsUrl: mapsUrl("日吉 大勝軒"),
  },
  {
    id: "hiyoshi-hamatora",
    name: "麺場 ハマトラ 日吉店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["塩とりそば", "つけそば特盛無料"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["塩", "つけ麺"],
    sceneTags: ["gap_time", "solo", "with_friends"],
    budgetMin: 850,
    budgetMax: 1150,
    signatureOrderName: "塩とりそば",
    signatureOrderPrice: 950,
    studentBudgetNote: "つけそばは特盛が無料。同じ予算でも満足度を上げやすい。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 3,
    lightness: 3,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 2,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "日吉駅から徒歩圏。キャンパスからも歩いて行ける距離。",
    whyThisShop: "塩とりそばとつけそばの二択で、その日の気分に合わせやすい。",
    recommendedMenu: "塩とりそば／つけそば（特盛無料）",
    tasteNotes: "鶏白湯の塩スープはやさしい味わい。つけそばは特盛が無料で量も選べる。",
    atmosphereNotes: "明るく入りやすい内装で、グループでの利用もしやすい。",
    beginnerNotes: "塩とりそばは初めてでも食べやすい味。つけそばは麺量を相談できる。",
    rulesNotes: "特盛は無料だが、食べきれる量を選ぶのが無難。",
    keioNotes: "友達と行っても、ひとりで行っても浮かない使いやすさがある。",
    recommendedFor: ["あっさりとがっつりで迷う人", "友達と行きたい人"],
    googleMapsUrl: mapsUrl("麺場ハマトラ 日吉店"),
  },
  {
    id: "hiyoshi-asuhon",
    name: "油そば屋 明日から本気出す 日吉店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["油そば専門", "変わり種あり"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["まぜそば"],
    sceneTags: ["solo", "gap_time", "after_class"],
    budgetMin: 750,
    budgetMax: 1000,
    signatureOrderName: "油そばDX",
    signatureOrderPrice: 900,
    studentBudgetNote: "スープなしで提供が早く、コスパも良い。空きコマ向き。",
    priceConfidence: "approximate",
    visualTone: "mazesoba",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "日吉駅から徒歩1分。2025年にオープンした油そば専門店。",
    whyThisShop: "日吉駅すぐの油そば専門店。麻婆油そばなど変化球も楽しめる。",
    recommendedMenu: "油そばDX",
    tasteNotes: "タレと油を麺に絡めて食べる油そば。卓上の酢やラー油で味変できる。",
    atmosphereNotes: "カジュアルで、一人でもさっと入れる。",
    beginnerNotes: "よく混ぜてから食べる。味が濃いと感じたら酢を足すと食べやすい。",
    rulesNotes: "油そばは提供が早い。にんにくや辛みは好みで調整できる。",
    keioNotes: "空きコマや一人飯で、さっと変化球を食べたい時に使いやすい新店。",
    recommendedFor: ["油そば・まぜそば好き", "短時間で食べたい人"],
    googleMapsUrl: mapsUrl("油そば屋 明日から本気出す 日吉店"),
  },
  {
    id: "hiyoshi-gatton",
    name: "がっとん 日吉店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["替え玉orライス無料", "コスパ重視"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["豚骨"],
    sceneTags: ["solo", "gap_time", "after_class"],
    budgetMin: 700,
    budgetMax: 950,
    signatureOrderName: "ラーメン",
    signatureOrderPrice: 800,
    studentBudgetNote: "替え玉かライスが無料。800円前後でしっかり満たせるコスパ番長。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 4,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "日吉駅から徒歩圏。",
    whyThisShop: "一杯で替え玉かライスが無料。日吉でコスパよく腹を満たせる博多豚骨。",
    recommendedMenu: "ラーメン（替え玉 or ライス無料）",
    tasteNotes: "まろやかな博多豚骨に細麺。替え玉でしっかり食べ進められる。",
    atmosphereNotes: "カウンター中心で、一人でも気軽に入れる。",
    beginnerNotes: "麺の硬さは「普通」でOK。無料サービスの替え玉かライスを活用したい。",
    rulesNotes: "替え玉またはライスが無料になることが多い。会計前に確認すると良い。",
    keioNotes: "安く腹を満たしたい時の鉄板。コスパ重視の学生に強い一軒。",
    recommendedFor: ["コスパ重視の人", "博多豚骨を安く食べたい人"],
    googleMapsUrl: mapsUrl("がっとん 日吉店 ラーメン"),
  },
  {
    id: "hiyoshi-shibatashoten",
    name: "柴田商店",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["博多系の魚介豚骨"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["豚骨"],
    sceneTags: ["solo", "gap_time"],
    budgetMin: 800,
    budgetMax: 1050,
    signatureOrderName: "ラーメン＋替え玉",
    signatureOrderPrice: 950,
    studentBudgetNote: "替え玉込みでも1,000円前後。しっかり食べても収まりやすい。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 4,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "日吉駅から徒歩圏。キャンパスからもアクセスしやすい。",
    whyThisShop: "家系でも二郎でもない、博多系の魚介豚骨が欲しい時の選択肢。",
    recommendedMenu: "ラーメン（替え玉付き）",
    tasteNotes: "魚介の出汁が効いた豚骨スープに細麺。替え玉でちょうどよく食べ進められる。",
    atmosphereNotes: "カウンター主体で、ひとりで黙々と食べるのに向いている。",
    beginnerNotes: "替え玉の量や硬さは好みで調整できる。まずは普通盛りで試すのがよい。",
    rulesNotes: "替え玉は麺だけの追加。スープが減る前に頼むのがコツ。",
    keioNotes: "日吉の家系・二郎に飽きた時の、もう一つの定番として覚えておきたい。",
    recommendedFor: ["博多系が好きな人", "ひとりで集中して食べたい人"],
    googleMapsUrl: mapsUrl("柴田商店 日吉"),
  },

  // ===== 三田・田町 =====
  {
    id: "mita-jiro",
    name: "ラーメン二郎 三田本店",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["二郎系の元祖", "三田の名物"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty", "no_fail"],
    budgetMin: 700,
    budgetMax: 950,
    signatureOrderName: "小ラーメン",
    signatureOrderPrice: 700,
    studentBudgetNote: "このボリュームで700円前後は破格。空腹で挑みたい。",
    priceConfidence: "approximate",
    visualTone: "jiro",
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 1,
    soloFriendly: 2,
    friendFriendly: 3,
    queueLevel: 5,
    speedLevel: 1,
    lateNight: false,
    keioStudentScore: 4,
    nearness: 3,
    accessNote: "都営三田駅から徒歩約9分、JR田町駅から徒歩約10分。三田キャンパスからも歩ける。",
    whyThisShop: "三田に来たなら一度は話題になる、二郎系の元祖本店。",
    recommendedMenu: "小ラーメン",
    tasteNotes: "豚の脂をまとった醤油ベースのスープに極太麺、山盛りの野菜とチャーシュー。",
    atmosphereNotes: "常連が多く、店内は黙々と食べる独特の空気感がある。",
    beginnerNotes: "初めては「小・にんにくなし」が無難。コールが早いので聞き取れなければ無言でもよい。",
    rulesNotes: "麺を残すのは避けたいマナー。完食できる量から挑戦するのがおすすめ。",
    keioNotes: "「行った」こと自体が話題になる、三田の名物的存在。",
    recommendedFor: ["二郎系経験者", "とにかく量を食べたい人"],
    googleMapsUrl: mapsUrl("ラーメン二郎 三田本店"),
  },
  {
    id: "mita-buguenka",
    name: "武源家",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["慶應三田キャンパスのすぐ前"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["after_class", "hearty", "no_fail"],
    budgetMin: 800,
    budgetMax: 1100,
    signatureOrderName: "ラーメン",
    signatureOrderPrice: 850,
    studentBudgetNote: "学生向けの値付けで通いやすい。キャンパス前という立地が強み。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 5,
    lightness: 1,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 5,
    nearness: 5,
    accessNote: "三田駅から徒歩約5分。慶應義塾大学三田キャンパスの目の前。",
    whyThisShop: "慶應三田キャンパスの真ん前。立地だけでもう理由になる家系。",
    recommendedMenu: "ラーメン",
    tasteNotes: "もっちりした太麺に、濃いめの豚骨醤油スープを合わせる横浜家系。",
    atmosphereNotes: "学生価格を意識した値付けで、気軽に入りやすい雰囲気。",
    beginnerNotes: "麺の硬さ・脂・味の濃さを聞かれることが多い。わからなければ「普通」で。",
    rulesNotes: "ライスサービスがある場合は会計時に確認すると良い。",
    keioNotes: "三田キャンパスのすぐ前で、授業の合間に行ける貴重な距離感。",
    recommendedFor: ["授業の合間に行きたい人", "三田で家系を食べたい人"],
    googleMapsUrl: mapsUrl("武源家 三田 ラーメン"),
  },
  {
    id: "mita-tsukemen",
    name: "三田製麺所 三田本店",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["つけ麺チェーンの本店"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["つけ麺"],
    sceneTags: ["hearty", "with_friends"],
    budgetMin: 900,
    budgetMax: 1250,
    signatureOrderName: "つけ麺＋大盛り",
    signatureOrderPrice: 1100,
    studentBudgetNote: "大盛りまで同料金。同じ値段なら大盛りにしない手はない。",
    priceConfidence: "approximate",
    visualTone: "tsukemen",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "三田駅・田町駅どちらからも徒歩圏。",
    whyThisShop: "全国展開するつけ麺チェーンの本店が、地元の三田にある。",
    recommendedMenu: "つけ麺（並〜大盛り同料金）",
    tasteNotes: "魚介豚骨の濃厚なつけ汁に極太麺。スープ割りで最後まで楽しめる。",
    atmosphereNotes: "テーブル席が中心で、グループでの利用にも向いている。",
    beginnerNotes: "麺量は大盛りまで同じ料金。初めては並盛りで様子を見るのがよい。",
    rulesNotes: "スープ割りは卓上のポットを使う形式。やり方は店員に聞けば教えてもらえる。",
    keioNotes: "ゼミやサークルの集合にも使える、テーブルの広さが利点。",
    recommendedFor: ["がっつり食べたい人", "友達と行きたい人"],
    googleMapsUrl: mapsUrl("三田製麺所 三田本店"),
  },
  {
    id: "mita-gorindo",
    name: "麺屋武蔵 五輪洞",
    area: "三田",
    station: "田町駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["麺屋武蔵の田町店", "つけ麺も強い"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["つけ麺"],
    sceneTags: ["after_class", "with_friends", "no_fail"],
    budgetMin: 1000,
    budgetMax: 1400,
    signatureOrderName: "つけ麺",
    signatureOrderPrice: 1150,
    studentBudgetNote: "名店チェーンらしい完成度。少し贅沢したい日に向く価格帯。",
    priceConfidence: "approximate",
    visualTone: "tsukemen",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "三田駅A3出口から徒歩約2分、田町駅から徒歩約4分。",
    whyThisShop: "麺屋武蔵の田町店。豚骨魚介の濃厚スープで、つけ麺もら〜麺も強い。",
    recommendedMenu: "つけ麺（武蔵ら〜麺も人気）",
    tasteNotes: "節や香味油を効かせた豚骨魚介の濃厚スープに、食べごたえのあるチャーシュー。",
    atmosphereNotes: "席数があり、ひとりでもグループでも入りやすい。",
    beginnerNotes: "メニューは豊富だが、看板のつけ麺から〜麺を選べば外さない。",
    rulesNotes: "トッピングは券売機で選べる。スープ割りができることが多い。",
    keioNotes: "三田・田町のどちらからも歩け、授業後に少し良いものを食べたい時に。",
    recommendedFor: ["濃厚なつけ麺が好きな人", "名店の安定感が欲しい人"],
    googleMapsUrl: mapsUrl("麺屋武蔵 五輪洞 田町"),
  },
  {
    id: "mita-ichizuitei",
    name: "博多一瑞亭 三田店",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["博多豚骨", "替え玉文化"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["豚骨"],
    sceneTags: ["solo", "gap_time", "after_class"],
    budgetMin: 750,
    budgetMax: 1050,
    signatureOrderName: "ラーメン＋替え玉",
    signatureOrderPrice: 850,
    studentBudgetNote: "替え玉込みでも1,000円前後。一人でさっと済ませやすい。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 4,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "三田駅から徒歩圏。",
    whyThisShop: "三田で本格的な博多豚骨と替え玉文化を、一人でさっと味わえる一軒。",
    recommendedMenu: "ラーメン（替え玉）",
    tasteNotes: "クリーミーな豚骨スープに細麺。替え玉で最後まで楽しめる。",
    atmosphereNotes: "カウンター主体で一人客が多く、気兼ねなく入れる。",
    beginnerNotes: "麺の硬さは「バリカタ〜普通」で。替え玉は食べ進めてから頼む。",
    rulesNotes: "替え玉は麺のみの追加。卓上の紅生姜や高菜で味変できる。",
    keioNotes: "三田で家系・二郎に偏らず、博多豚骨を一人で食べたい時に。",
    recommendedFor: ["博多豚骨が好きな人", "一人で替え玉を楽しみたい人"],
    googleMapsUrl: mapsUrl("博多一瑞亭 三田店"),
  },
  {
    id: "mita-yattoko",
    name: "やっとこ 三田店",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["カウンターのみの行列店"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["味噌", "豚骨"],
    sceneTags: ["solo", "gap_time"],
    budgetMin: 850,
    budgetMax: 1100,
    signatureOrderName: "ラーメン（みそ）",
    signatureOrderPrice: 1000,
    studentBudgetNote: "味噌の満足感に対して納得の価格。並ぶ価値はある。",
    priceConfidence: "approximate",
    visualTone: "miso",
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 3,
    soloFriendly: 4,
    friendFriendly: 3,
    queueLevel: 4,
    speedLevel: 2,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "三田駅から徒歩圏。カウンターのみの小さな店なので並ぶ前提で。",
    whyThisShop: "赤・白・麦の3種の味噌をブレンドした、ここにしかない味噌だれが軸。",
    recommendedMenu: "ラーメン（みそ）",
    tasteNotes: "長時間煮込んだ豚骨魚介スープに、3種の味噌をブレンドしたタレを合わせる。",
    atmosphereNotes: "カウンターのみの小さな店構えで、ひとりでの利用が中心。",
    beginnerNotes: "メニューはみそラーメンが基本。並んでいても回転は早めで待ちやすい。",
    rulesNotes: "ピーク時は行列ができやすい。時間をずらすと並ばずに入れることもある。",
    keioNotes: "三田で「味噌が食べたい日」の定番。学生からの支持も厚い。",
    recommendedFor: ["味噌ラーメンが好きな人", "並んでも食べたい味がある人"],
    googleMapsUrl: mapsUrl("やっとこ 三田店"),
  },
  {
    id: "mita-rikka",
    name: "らぁ麺 六花",
    area: "三田",
    station: "田町駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["田町の淡麗系"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["淡麗", "醤油"],
    sceneTags: ["gap_time", "solo", "no_fail"],
    budgetMin: 900,
    budgetMax: 1150,
    signatureOrderName: "醤油らぁ麺",
    signatureOrderPrice: 1000,
    studentBudgetNote: "淡麗系として標準的な価格。質を考えれば納得感がある。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 2,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 3,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 3,
    accessNote: "田町駅から徒歩圏。三田キャンパスからは少し歩く距離感。",
    whyThisShop: "田町で澄んだ醤油らぁ麺を探しているなら、評価の高いここへ。",
    recommendedMenu: "醤油らぁ麺",
    tasteNotes: "鶏ガラと魚介を合わせた透明感のあるスープに、旨味の層を重ねた味わい。",
    atmosphereNotes: "落ち着いた内装で、ひとりでもゆっくり食べやすい。",
    beginnerNotes: "メニューがわかりやすく、初めてでも基本の醤油らぁ麺を頼めば間違いない。",
    rulesNotes: "特別なルールはなし。",
    keioNotes: "家系・二郎に偏りがちな三田・田町で、あっさり系を探す時の候補。",
    recommendedFor: ["あっさり系が好きな人", "ひとりでゆっくりしたい人"],
    googleMapsUrl: mapsUrl("らぁ麺 六花 田町"),
  },
  {
    id: "mita-kingken",
    name: "汁なし担担麺専門 キング軒 東京店",
    area: "三田",
    station: "芝公園駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["広島発の汁なし担担麺"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["担々麺"],
    sceneTags: ["solo", "gap_time"],
    budgetMin: 800,
    budgetMax: 1100,
    signatureOrderName: "汁なし担担麺",
    signatureOrderPrice: 900,
    studentBudgetNote: "汁なしで提供が早く、しびれと旨みのバランスが良い。",
    priceConfidence: "approximate",
    visualTone: "other",
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 3,
    soloFriendly: 4,
    friendFriendly: 3,
    queueLevel: 3,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 3,
    accessNote: "芝公園駅から徒歩圏。三田駅からも歩ける距離。",
    whyThisShop: "広島発の汁なし担担麺の専門店。痺れる花椒と挽き肉が後を引く。",
    recommendedMenu: "汁なし担担麺（追い飯）",
    tasteNotes: "タレと挽き肉、花椒のしびれを麺に絡める汁なしスタイル。追い飯で〆る。",
    atmosphereNotes: "カウンター中心で回転が早い。",
    beginnerNotes: "よく混ぜてから食べる。辛さ・痺れは注文時に調整できる。",
    rulesNotes: "30回以上混ぜるのが推奨。残ったタレに追い飯を入れるのが定番。",
    keioNotes: "三田・芝公園エリアで、ラーメンとは違う一杯を食べたい時の変化球。",
    recommendedFor: ["担々麺・痺れ系が好きな人", "変わり種を試したい人"],
    googleMapsUrl: mapsUrl("汁なし担担麺 キング軒 東京 芝公園"),
  },

  // ===== 横浜 =====
  {
    id: "yokohama-yoshimuraya",
    name: "家系総本山 吉村家",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["家系ラーメンの発祥店"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["hearty", "no_fail"],
    budgetMin: 900,
    budgetMax: 1150,
    signatureOrderName: "ラーメン",
    signatureOrderPrice: 1000,
    studentBudgetNote: "総本山を体験する価値ありの一杯。並ぶ時間も込みで考えたい。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 5,
    lightness: 1,
    volume: 4,
    beginnerFriendly: 3,
    soloFriendly: 3,
    friendFriendly: 4,
    queueLevel: 5,
    speedLevel: 1,
    lateNight: false,
    keioStudentScore: 4,
    nearness: 4,
    accessNote: "横浜駅西口から徒歩約6分。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "家系ラーメン発祥の総本山。一度は行っておきたい原点の一杯。",
    recommendedMenu: "ラーメン",
    tasteNotes: "豚骨と鶏ガラを長時間炊いた濃厚でクリーミーなスープに、醤油ダレのキレ。",
    atmosphereNotes: "行列が日常の人気店で、活気のある雰囲気。",
    beginnerNotes: "並ぶ前提で行くのが基本。コールは「普通」でまず注文すれば失敗しない。",
    rulesNotes: "並んでいる間にコール（麺・脂・味の濃さ）を聞かれることがあるので考えておくとスムーズ。",
    keioNotes: "横浜で飲んだ後や、家系の原点を知りたい時に足を伸ばす価値がある。",
    recommendedFor: ["家系の原点を知りたい人", "並んででも食べたい人"],
    googleMapsUrl: mapsUrl("家系総本山 吉村家 横浜"),
  },
  {
    id: "yokohama-tonzan",
    name: "豚山 横浜西口店",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["二郎系インスパイアの全国チェーン"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty", "after_drinking"],
    budgetMin: 800,
    budgetMax: 1050,
    signatureOrderName: "ラーメン",
    signatureOrderPrice: 950,
    studentBudgetNote: "トッピング自由でこの価格はお得。飲み後の〆にも。",
    priceConfidence: "approximate",
    visualTone: "jiro",
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 2,
    soloFriendly: 3,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 2,
    lateNight: true,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "横浜駅西口エリア。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "ヤサイ・アブラ・ニンニクを自分で選べる、二郎系インスパイアの定番チェーン。",
    recommendedMenu: "ラーメン（野菜・アブラ・にんにく選択制）",
    tasteNotes: "豚骨醤油の濃厚スープに極太麺。トッピングの量を自分で調整できる。",
    atmosphereNotes: "深夜まで営業しており、横浜での飲み帰りの利用も多い。",
    beginnerNotes: "コールに慣れていなければ「野菜普通」で頼めば調整しやすい。",
    rulesNotes: "店舗ごとに細かいコールの形式が異なるので、貼り紙を確認すると安心。",
    keioNotes: "横浜で飲んだ後、〆の一杯としてがっつり食べたい時の選択肢。",
    recommendedFor: ["飲んだ後にがっつり食べたい人", "二郎系インスパイアを試したい人"],
    googleMapsUrl: mapsUrl("豚山 横浜西口店"),
  },
  {
    id: "yokohama-busou",
    name: "つけ麺や 武双",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["横浜駅直結ヨドバシ地下", "濃厚つけ麺"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["つけ麺"],
    sceneTags: ["solo", "with_friends", "gap_time"],
    budgetMin: 950,
    budgetMax: 1300,
    signatureOrderName: "つけ麺",
    signatureOrderPrice: 1100,
    studentBudgetNote: "駅直結で本格つけ麺。乗り換えついでに寄りやすいのが強み。",
    priceConfidence: "approximate",
    visualTone: "tsukemen",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "横浜駅直結のヨドバシ横浜地下。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "横浜駅直結で食べられる、動物系の旨みを効かせた濃厚つけ麺。",
    recommendedMenu: "つけ麺",
    tasteNotes: "動物系の旨みを効かせた濃厚つけ汁に太めの麺。ボリュームも十分。",
    atmosphereNotes: "駅直結で立ち寄りやすく、一人でも入りやすい。",
    beginnerNotes: "麺量は選べることが多い。初めては並盛りで様子を見るとよい。",
    rulesNotes: "スープ割りができる。卓上の案内に従えばよい。",
    keioNotes: "横浜駅の乗り換えや帰り道に、しっかりつけ麺を食べたい時に便利。",
    recommendedFor: ["濃厚つけ麺が好きな人", "駅近で済ませたい人"],
    googleMapsUrl: mapsUrl("つけ麺や 武双 横浜"),
  },
  {
    id: "yokohama-tori",
    name: "自家製麺 酉",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["横浜駅直結アソビル内", "鶏ベースの二郎系インスパイア"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty", "after_drinking"],
    budgetMin: 850,
    budgetMax: 1100,
    signatureOrderName: "ラーメン",
    signatureOrderPrice: 1000,
    studentBudgetNote: "鶏ベースの二郎系をこの価格で。駅直結のアクセスも込みで。",
    priceConfidence: "approximate",
    visualTone: "jiro",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 3,
    soloFriendly: 3,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 2,
    lateNight: true,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "横浜駅直結のアソビル内。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "二郎系では珍しく、豚ではなく鶏でスープとトッピングを組んでいる。",
    recommendedMenu: "ラーメン",
    tasteNotes: "鶏を使った濃厚スープに極太麺。豚不使用ならではの後味の軽さがある。",
    atmosphereNotes: "アソビル内にあり、駅直結で雨の日でもアクセスしやすい。",
    beginnerNotes: "二郎系特有のコールはあるが、鶏ベースで重さは抑えめなので試しやすい。",
    rulesNotes: "トッピングのコールは店内の案内に従えば問題ない。",
    keioNotes: "横浜での集まりの後、雨でも駅から濡れずに行けるのが利点。",
    recommendedFor: ["二郎系を軽めに試したい人", "駅直結の店を探している人"],
    googleMapsUrl: mapsUrl("自家製麺 酉 横浜 アソビル"),
  },
  {
    id: "yokohama-afuri",
    name: "AFURI 横浜ジョイナス",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["柚子塩らーめんの人気店", "駅直結"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["淡麗", "塩"],
    sceneTags: ["solo", "with_friends", "no_fail"],
    budgetMin: 950,
    budgetMax: 1250,
    signatureOrderName: "柚子塩らーめん",
    signatureOrderPrice: 1200,
    studentBudgetNote: "淡麗系のなかではやや高め。その分の上質さはある。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 2,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 5,
    accessNote: "横浜駅直結の商業施設内。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "駅直結で迷わず行ける、柚子の香る淡麗系の人気店。",
    recommendedMenu: "柚子塩らーめん",
    tasteNotes: "鶏や魚介の出汁感に柚子の香りを効かせた、軽やかで澄んだ一杯。",
    atmosphereNotes: "明るく洗練された内装で、ひとりでも友達同士でも入りやすい。",
    beginnerNotes: "メニュー名がわかりやすく、写真付きの券売機で迷わず選べる。",
    rulesNotes: "特別なルールはなし。",
    keioNotes: "横浜で「重い系には疲れた」時の、あっさり系の正解。",
    recommendedFor: ["あっさり系が好きな人", "初めて横浜でラーメンを探す人"],
    googleMapsUrl: mapsUrl("AFURI 横浜ジョイナス"),
  },
  {
    id: "yokohama-honmarutei",
    name: "塩らー麺 本丸亭 横浜店",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市神奈川区",
    prefecture: "神奈川県",
    communityTags: ["横浜西口の塩の名店"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["塩", "淡麗"],
    sceneTags: ["solo", "no_fail", "gap_time"],
    budgetMin: 900,
    budgetMax: 1200,
    signatureOrderName: "塩らー麺",
    signatureOrderPrice: 1000,
    studentBudgetNote: "重い系に疲れた日に。上品だが満足感はしっかりある。",
    priceConfidence: "approximate",
    visualTone: "tanrei",
    richness: 2,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "横浜駅西口から徒歩圏。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "横浜西口で塩スープといえばここ。澄んだ旨みと手もみ麺が軽やか。",
    recommendedMenu: "塩らー麺",
    tasteNotes: "鶏と魚介の澄んだ塩スープに、国産小麦の手もみちぢれ麺。",
    atmosphereNotes: "落ち着いた雰囲気で、ひとりでもゆっくり食べられる。",
    beginnerNotes: "メニューがわかりやすく、基本の塩らー麺で間違いない。",
    rulesNotes: "特別なルールはなし。",
    keioNotes: "横浜であっさり上品な一杯を食べたい時の安定択。",
    recommendedFor: ["あっさり塩が好きな人", "上品な一杯を食べたい人"],
    googleMapsUrl: mapsUrl("塩らー麺 本丸亭 横浜店"),
  },
  {
    id: "yokohama-machidashoten",
    name: "横浜家系ラーメン 町田商店 横浜店",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市神奈川区",
    prefecture: "神奈川県",
    communityTags: ["家系チェーンの安定感"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["after_class", "hearty", "no_fail"],
    budgetMin: 800,
    budgetMax: 1100,
    signatureOrderName: "ラーメン＋ライス",
    signatureOrderPrice: 950,
    studentBudgetNote: "ライスが進む濃いめスープ。学生の腹を満たしやすい。",
    priceConfidence: "approximate",
    visualTone: "iekei",
    richness: 5,
    lightness: 1,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "横浜駅西口・鶴屋町エリア。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "全国展開する家系チェーンの横浜店。安定の濃さでライスが進む。",
    recommendedMenu: "ラーメン（ライス付き）",
    tasteNotes: "豚骨・鶏ガラに醤油ダレ、中太ストレート麺の王道家系。海苔とほうれん草。",
    atmosphereNotes: "明るく入りやすい、チェーンらしい清潔な店内。",
    beginnerNotes: "麺の硬さ・脂・濃さは「普通」でOK。初めての家系にも向く。",
    rulesNotes: "卓上の調味料や生姜で味変できる。ライスサービスがある場合も。",
    keioNotes: "横浜で迷ったら入りやすい家系。チェーンの安定感で失敗しにくい。",
    recommendedFor: ["家系初心者", "濃いめをライスで食べたい人"],
    googleMapsUrl: mapsUrl("横浜家系ラーメン 町田商店 横浜店"),
  },
  {
    id: "yokohama-burabura",
    name: "油そば専門店 ぶらぶら 横浜本店",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["油そば専門店", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["まぜそば"],
    sceneTags: ["with_friends", "after_club", "after_drinking"],
    budgetMin: 750,
    budgetMax: 1000,
    signatureOrderName: "油そば（並）",
    signatureOrderPrice: 850,
    studentBudgetNote: "並でも満足感があり財布に優しい。深夜の〆にもちょうどいい。",
    priceConfidence: "approximate",
    visualTone: "mazesoba",
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 3,
    friendFriendly: 5,
    queueLevel: 2,
    speedLevel: 3,
    lateNight: true,
    keioStudentScore: 3,
    nearness: 4,
    accessNote: "横浜駅西口から徒歩約4分。日吉・三田からは電車で15〜20分ほど。",
    whyThisShop: "スープのない油そば専門店。混ぜて食べる一杯を友達と気軽に。",
    recommendedMenu: "油そば（並）",
    tasteNotes: "タレと油を麺によく絡めて食べる、スープなしの油そばスタイル。",
    atmosphereNotes: "カジュアルな雰囲気で、グループでの利用がしやすい。",
    beginnerNotes: "届いたらまず最初によく混ぜるのがポイント。やり方は店員も教えてくれる。",
    rulesNotes: "酢やラー油など卓上の調味料で味変できる。",
    keioNotes: "サークルの集まりや飲んだ後、友達と軽く〆たい時に向いている。",
    recommendedFor: ["友達と行きたい人", "深夜の〆に油そばを食べたい人"],
    googleMapsUrl: mapsUrl("油そば専門店 ぶらぶら 横浜本店"),
  },
];

export function getShopById(id: string): Shop | undefined {
  return SHOPS.find((shop) => shop.id === id);
}

export function getAllAreas(): string[] {
  return Array.from(new Set(SHOPS.map((shop) => shop.area)));
}

export function getAllGenres(): string[] {
  return Array.from(new Set(SHOPS.flatMap((shop) => shop.genres)));
}
