import type { Shop } from "./types";

function mapsUrl(query: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

export const SHOPS: Shop[] = [
  {
    id: "hiyoshi-iekei-bansho",
    name: "日吉家系 万翔",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["日吉キャンパス徒歩3分", "テスト前の鉄板"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系", "豚骨醤油"],
    sceneTags: ["after_class", "hearty", "no_fail"],
    budgetMin: 800,
    budgetMax: 1100,
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 4,
    soloFriendly: 5,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 5,
    campusWalkMin: 3,
    recommendedMenu: "ラーメン 海苔増し・ほうれん草増し",
    tasteNotes: "とろみのある豚骨醤油スープに太めの麺。海苔で巻いて食べると味変できる。",
    atmosphereNotes: "カウンター中心で常に賑やか。一人客も学生グループも自然に混ざる空気感。",
    beginnerNotes: "卓上の操作は不要。注文時に「麺の硬さ」だけ聞かれるので「普通」と言えば安心。",
    rulesNotes: "ライス無料券をもらえる日があるので会計時に確認すると得。",
    keioNotes: "日吉キャンパスから徒歩3分。授業終わりにそのまま直行できる距離感が強み。",
    recommendedFor: ["授業終わりに即直行したい人", "がっつり食べたい人", "家系初心者"],
    googleMapsUrl: mapsUrl("日吉家系 万翔 日吉駅"),
  },
  {
    id: "hiyoshi-jiro-kaijin",
    name: "日吉二郎系 魁神",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["サークル後の定番", "野菜マシマシ文化"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty", "after_club"],
    budgetMin: 750,
    budgetMax: 1000,
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 2,
    soloFriendly: 3,
    friendFriendly: 3,
    queueLevel: 4,
    speedLevel: 2,
    lateNight: false,
    keioStudentScore: 4,
    campusWalkMin: 6,
    recommendedMenu: "小ラーメン ニンニクアブラ",
    tasteNotes: "豚と煮干しの濃厚スープに極太麺。ニンニクの量で印象が大きく変わる。",
    atmosphereNotes: "店内は無言で食べる人が多く、独特の緊張感がある。常連が多い。",
    beginnerNotes: "コールは「ニンニク・アブラ・カラメ」の有無を聞かれる。初めてなら全部「少なめ」でOK。",
    rulesNotes: "麺を残すのはマナー違反とされがち。小ラーメンから試すのが安全。",
    keioNotes: "サークルの打ち上げ後にそのまま流れる学生が多く、深夜でなくても賑わう。",
    recommendedFor: ["二郎系に挑戦したい人", "ガッツリ食べたい人", "クセのある店が好きな人"],
    googleMapsUrl: mapsUrl("日吉二郎系 魁神 日吉駅"),
  },
  {
    id: "hiyoshi-tanrei-shizuku",
    name: "日吉淡麗 しずく",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["女子学生にも人気", "一人飯の定番"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["淡麗", "醤油"],
    sceneTags: ["gap_time", "solo", "no_fail"],
    budgetMin: 850,
    budgetMax: 1050,
    richness: 2,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 4,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 4,
    campusWalkMin: 5,
    recommendedMenu: "鶏白湯淡麗そば",
    tasteNotes: "鶏と魚介のだしが効いた澄んだスープ。後味が軽く、毎日食べても飽きない。",
    atmosphereNotes: "明るい内装でひとりでも入りやすい。カウンターは半個室風で居心地が良い。",
    beginnerNotes: "メニューはシンプルで、券売機の写真を見れば迷わない。",
    rulesNotes: "特になし。トッピングの追加は卓上のQRから注文できる。",
    keioNotes: "空きコマでもさっと食べて出られる早さが学生に好評。",
    recommendedFor: ["あっさり系が好きな人", "一人でゆっくりしたい人", "空きコマ利用"],
    googleMapsUrl: mapsUrl("日吉淡麗 しずく 日吉駅"),
  },
  {
    id: "hiyoshi-mazesoba-en",
    name: "日吉まぜそば 縁",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["友達と行く率No.1", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["まぜそば"],
    sceneTags: ["with_friends", "after_club", "after_drinking"],
    budgetMin: 900,
    budgetMax: 1200,
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 5,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: true,
    keioStudentScore: 4,
    campusWalkMin: 4,
    recommendedMenu: "特製まぜそば 卵黄トッピング",
    tasteNotes: "魚粉とタレが絡んだ濃いめの味付け。卵黄を絡めるとマイルドになる。",
    atmosphereNotes: "テーブル席が多く、グループでも入りやすい。BGMが流れる明るい店内。",
    beginnerNotes: "まぜそばは届いたらすぐ「よく混ぜる」のが鉄則。お店の人も教えてくれる。",
    rulesNotes: "替え玉ではなく「追い飯」がある店なので、最後にスープ感覚で楽しめる。",
    keioNotes: "深夜1時まで営業しているため、飲み会の後にそのまま流れてくる学生が多い。",
    recommendedFor: ["友達と盛り上がりたい人", "飲み会の〆", "サークル後"],
    googleMapsUrl: mapsUrl("日吉まぜそば 縁 日吉駅"),
  },
  {
    id: "hiyoshi-shio-nagidori",
    name: "日吉塩らーめん 凪鳥",
    area: "日吉",
    station: "日吉駅",
    city: "横浜市港北区",
    prefecture: "神奈川県",
    communityTags: ["朝練後にも", "あっさり派の避難所"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["塩"],
    sceneTags: ["gap_time", "solo"],
    budgetMin: 750,
    budgetMax: 950,
    richness: 2,
    lightness: 4,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 5,
    lateNight: false,
    keioStudentScore: 3,
    campusWalkMin: 7,
    recommendedMenu: "塩らーめん 柚子添え",
    tasteNotes: "鶏ガラベースの透明スープに柚子の香りがアクセント。胃に優しい味わい。",
    atmosphereNotes: "カウンター7席のみの小さな店。回転が速く一人でもさっと座れる。",
    beginnerNotes: "メニューが塩らーめん中心で迷わない。トッピングはねぎとメンマのみ。",
    rulesNotes: "ピーク時は相席になることがある。一人客同士の相席が前提の作り。",
    keioNotes: "提供が早いので、次の授業まで20分しかない空きコマでも安心して入れる。",
    recommendedFor: ["あっさり系が好きな人", "短時間で済ませたい人", "一人飯"],
    googleMapsUrl: mapsUrl("日吉塩らーめん 凪鳥 日吉駅"),
  },
  {
    id: "mita-iekei-kosho",
    name: "三田家系 虎将",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["三田キャンパス徒歩4分", "OB訪問帰りにも"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["after_class", "hearty", "no_fail"],
    budgetMin: 850,
    budgetMax: 1150,
    richness: 5,
    lightness: 1,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: false,
    keioStudentScore: 5,
    campusWalkMin: 4,
    recommendedMenu: "ラーメン 小ライス付き",
    tasteNotes: "濃厚な豚骨醤油スープと厚めのチャーシューが特徴。満足感が高い一杯。",
    atmosphereNotes: "スーツ姿の社会人と学生が半々。落ち着いた雰囲気で長居もしやすい。",
    beginnerNotes: "「ライス無料」の貼り紙があるが、量に自信がなければ普通盛りで十分。",
    rulesNotes: "卓上のキャベツ漬けはセルフサービス。会計は先払い制。",
    keioNotes: "三田キャンパスから徒歩4分で、授業後やOB訪問の合間に寄りやすい。",
    recommendedFor: ["授業終わりに即直行したい人", "がっつり食べたい人", "家系好き"],
    googleMapsUrl: mapsUrl("三田家系 虎将 三田駅"),
  },
  {
    id: "mita-tsukemen-godo",
    name: "三田つけ麺 剛堂",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["ゼミ後の集合場所", "大盛り無料"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["つけ麺"],
    sceneTags: ["hearty", "with_friends"],
    budgetMin: 950,
    budgetMax: 1300,
    richness: 4,
    lightness: 2,
    volume: 5,
    beginnerFriendly: 3,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 4,
    speedLevel: 2,
    lateNight: false,
    keioStudentScore: 4,
    campusWalkMin: 6,
    recommendedMenu: "特製つけ麺 大盛り",
    tasteNotes: "魚介豚骨の濃厚なつけ汁に太麺がよく絡む。最後はスープ割りで温かく楽しめる。",
    atmosphereNotes: "テーブル席中心で4〜6人グループでも入りやすい広めの店内。",
    beginnerNotes: "麺の量は「普通・大盛り・特盛り」から選べる。大盛りまでは同一料金。",
    rulesNotes: "「スープ割り」を頼むとレジ横のポットを使ってよいか聞かれるので素直に従えばよい。",
    keioNotes: "テーブルが広くゼミやサークルの集合場所として使われがち。",
    recommendedFor: ["がっつり食べたい人", "友達と行きたい人", "つけ麺好き"],
    googleMapsUrl: mapsUrl("三田つけ麺 剛堂 三田駅"),
  },
  {
    id: "mita-miso-yukidoke",
    name: "三田味噌 雪解け",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["冬の人気メニューあり", "落ち着いた内装"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["味噌"],
    sceneTags: ["gap_time", "solo", "with_friends"],
    budgetMin: 900,
    budgetMax: 1150,
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 5,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 2,
    speedLevel: 4,
    lateNight: false,
    keioStudentScore: 3,
    campusWalkMin: 8,
    recommendedMenu: "味噌バターコーンらーめん",
    tasteNotes: "甘みのある味噌スープにバターとコーンの組み合わせが定番人気。",
    atmosphereNotes: "木目調の落ち着いた内装。一人でもグループでも浮かない雰囲気。",
    beginnerNotes: "辛さ調整ができ「普通・中辛・辛口」から選べるので苦手な人は普通でOK。",
    rulesNotes: "特になし。バターは追加無料の場合が多いので店員に確認すると良い。",
    keioNotes: "回転が早く、空きコマの合間でも余裕を持って戻れる。",
    recommendedFor: ["味噌好き", "あっさりとこってりの中間が好きな人", "空きコマ利用"],
    googleMapsUrl: mapsUrl("三田味噌 雪解け 三田駅"),
  },
  {
    id: "mita-shoyu-kotobuki",
    name: "三田醤油 寿",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["老舗の安心感", "回転の早さNo.1"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["醤油", "淡麗"],
    sceneTags: ["gap_time", "solo", "no_fail"],
    budgetMin: 750,
    budgetMax: 950,
    richness: 2,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 1,
    speedLevel: 5,
    lateNight: false,
    keioStudentScore: 3,
    campusWalkMin: 3,
    recommendedMenu: "醤油らーめん",
    tasteNotes: "昔ながらの澄んだ醤油スープ。シンプルだが出汁の旨味がしっかり感じられる。",
    atmosphereNotes: "昭和から続く佇まいのカウンター店。常連の社会人も多く落ち着く。",
    beginnerNotes: "メニューが少なく迷わない。基本の醤油らーめんを頼めば間違いない。",
    rulesNotes: "現金のみの場合があるので念のため確認すると安心。",
    keioNotes: "三田キャンパスから徒歩3分。提供も早く空きコマの強い味方。",
    recommendedFor: ["短時間で済ませたい人", "あっさり系が好きな人", "並びたくない人"],
    googleMapsUrl: mapsUrl("三田醤油 寿 三田駅"),
  },
  {
    id: "mita-yozakura-akari",
    name: "三田夜桜 灯",
    area: "三田",
    station: "三田駅",
    city: "港区",
    prefecture: "東京都",
    communityTags: ["飲み会の〆", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["醤油", "まぜそば"],
    sceneTags: ["after_drinking", "after_club", "with_friends"],
    budgetMin: 850,
    budgetMax: 1200,
    richness: 3,
    lightness: 3,
    volume: 3,
    beginnerFriendly: 4,
    soloFriendly: 3,
    friendFriendly: 5,
    queueLevel: 2,
    speedLevel: 3,
    lateNight: true,
    keioStudentScore: 4,
    campusWalkMin: 5,
    recommendedMenu: "醤油まぜそば 味玉トッピング",
    tasteNotes: "甘辛いタレのまぜそばと、すっきりした醤油らーめんの2本柱。飲んだ後でも食べやすい。",
    atmosphereNotes: "照明が落とされた落ち着いたバルのような内装。グループ利用が多い。",
    beginnerNotes: "酔っていても券売機が大きくシンプルなので注文に困らない。",
    rulesNotes: "深夜帯は提供が少しゆっくりになることがあるので時間に余裕を持つと良い。",
    keioNotes: "深夜2時まで営業しており、三田での飲み会後の定番ルートになっている。",
    recommendedFor: ["飲み後の〆", "友達と盛り上がりたい人", "深夜まで営業している店を探している人"],
    googleMapsUrl: mapsUrl("三田夜桜 灯 三田駅"),
  },
  {
    id: "yokohama-iekei-oukan",
    name: "横浜家系 王冠",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["飲み後の定番", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["家系"],
    sceneTags: ["hearty", "after_drinking", "no_fail"],
    budgetMin: 850,
    budgetMax: 1150,
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 4,
    soloFriendly: 4,
    friendFriendly: 4,
    queueLevel: 4,
    speedLevel: 2,
    lateNight: true,
    keioStudentScore: 4,
    campusWalkMin: 25,
    recommendedMenu: "ラーメン 全部マシ",
    tasteNotes: "濃厚な豚骨醤油スープに極太麺。トッピングを盛るほど満足感が増す王道家系。",
    atmosphereNotes: "横浜駅西口の繁華街にあり、終電前の客で賑わう。活気のある店内。",
    beginnerNotes: "「ニンニク・脂・固さ」のコールがあるが、無言でも普通で提供してもらえる。",
    rulesNotes: "深夜は行列ができやすいので、並びたくない場合は時間をずらすのがおすすめ。",
    keioNotes: "横浜での飲み会帰りに寄りやすく、慶應生のグループもよく利用する。",
    recommendedFor: ["飲み後の〆", "がっつり食べたい人", "家系好き"],
    googleMapsUrl: mapsUrl("横浜家系 王冠 横浜駅"),
  },
  {
    id: "yokohama-jiro-tekken",
    name: "横浜二郎系 鉄拳",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["玄人向け", "完食できたら称賛される"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["二郎系"],
    sceneTags: ["hearty"],
    budgetMin: 800,
    budgetMax: 1000,
    richness: 5,
    lightness: 1,
    volume: 5,
    beginnerFriendly: 1,
    soloFriendly: 2,
    friendFriendly: 3,
    queueLevel: 5,
    speedLevel: 1,
    lateNight: false,
    keioStudentScore: 3,
    campusWalkMin: 20,
    recommendedMenu: "小ラーメン",
    tasteNotes: "圧倒的な量とニンニクの効いたスープ。完食すると常連から一目置かれる。",
    atmosphereNotes: "常連の独自ルールが多く、初めてだと少し緊張する空気感。",
    beginnerNotes: "初めての場合は「小ラーメン・ニンニクなし」が無難。無理に完食を狙わない方がよい。",
    rulesNotes: "コールは早口で聞かれるので、聞き取れなければ「そのままで」と伝えればよい。",
    keioNotes: "玄人向けだが完食レポートをLINEで自慢する学生も多い、いわば挑戦枠。",
    recommendedFor: ["二郎系の経験者", "とにかく量を食べたい人", "クセが強い店が好きな人"],
    googleMapsUrl: mapsUrl("横浜二郎系 鉄拳 横浜駅"),
  },
  {
    id: "yokohama-tonkotsu-hibiki",
    name: "横浜豚骨 響",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["一人飲みの後に", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["豚骨"],
    sceneTags: ["solo", "after_drinking", "gap_time"],
    budgetMin: 750,
    budgetMax: 1000,
    richness: 4,
    lightness: 2,
    volume: 3,
    beginnerFriendly: 4,
    soloFriendly: 5,
    friendFriendly: 4,
    queueLevel: 3,
    speedLevel: 4,
    lateNight: true,
    keioStudentScore: 3,
    campusWalkMin: 18,
    recommendedMenu: "豚骨らーめん 替え玉付き",
    tasteNotes: "濃厚だがクセの少ない豚骨スープ。替え玉文化があり食べ進めやすい。",
    atmosphereNotes: "横並びカウンターで一人客が多く、誰にも干渉されず食べられる。",
    beginnerNotes: "替え玉は無料の場合が多いので、まず普通盛りで頼んで様子を見るのがおすすめ。",
    rulesNotes: "替え玉は「麺だけ」追加なので、スープが少なくなったら早めに頼むのがコツ。",
    keioNotes: "横浜での一人飲みの後、ふらっと寄れる距離感とカウンター構成が一人飯に向く。",
    recommendedFor: ["一人で入りやすい店を探している人", "深夜まで開いている店", "替え玉でしっかり食べたい人"],
    googleMapsUrl: mapsUrl("横浜豚骨 響 横浜駅"),
  },
  {
    id: "yokohama-tanrei-suisho",
    name: "横浜淡麗 水晶",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["女子学生に人気", "あっさり派の聖地"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["淡麗", "塩"],
    sceneTags: ["gap_time", "solo", "no_fail"],
    budgetMin: 900,
    budgetMax: 1100,
    richness: 1,
    lightness: 5,
    volume: 2,
    beginnerFriendly: 5,
    soloFriendly: 5,
    friendFriendly: 3,
    queueLevel: 2,
    speedLevel: 5,
    lateNight: false,
    keioStudentScore: 3,
    campusWalkMin: 22,
    recommendedMenu: "鶏塩淡麗そば",
    tasteNotes: "透明感のある鶏白湯スープ。塩味は控えめで素材の旨味を活かした味わい。",
    atmosphereNotes: "カフェのような明るい内装で、女性一人でも入りやすい雰囲気。",
    beginnerNotes: "メニューが少なく注文に迷わない。トッピングは全て単品追加できる。",
    rulesNotes: "特になし。提供が早いので回転率も高い。",
    keioNotes: "あっさり系を探す慶應生からの支持が高く、並ばずに入れることが多い。",
    recommendedFor: ["あっさり系が好きな人", "並びたくない人", "短時間で済ませたい人"],
    googleMapsUrl: mapsUrl("横浜淡麗 水晶 横浜駅"),
  },
  {
    id: "yokohama-mazesoba-rakuen",
    name: "横浜まぜそば 楽園",
    area: "横浜",
    station: "横浜駅",
    city: "横浜市西区",
    prefecture: "神奈川県",
    communityTags: ["サークル打ち上げの定番", "深夜営業"],
    targetUniversities: ["慶應義塾大学"],
    genres: ["まぜそば", "つけ麺"],
    sceneTags: ["with_friends", "after_club", "after_drinking"],
    budgetMin: 900,
    budgetMax: 1250,
    richness: 4,
    lightness: 2,
    volume: 4,
    beginnerFriendly: 4,
    soloFriendly: 3,
    friendFriendly: 5,
    queueLevel: 3,
    speedLevel: 3,
    lateNight: true,
    keioStudentScore: 4,
    campusWalkMin: 19,
    recommendedMenu: "特製まぜそば 大盛り",
    tasteNotes: "魚粉とニンニク油が効いた濃厚なタレ。混ぜるほどに香りが立つ一杯。",
    atmosphereNotes: "大人数席があり、団体での貸切利用も可能。賑やかな雰囲気が好まれる。",
    beginnerNotes: "麺が届いたらすぐにしっかり混ぜるのがポイント。混ぜ方は店員が教えてくれる。",
    rulesNotes: "団体利用の場合は事前に電話で席を確保しておくとスムーズ。",
    keioNotes: "サークルの打ち上げ後にそのまま流れ込む大人数グループが多い。",
    recommendedFor: ["友達と盛り上がりたい人", "サークル後", "深夜まで開いている店を探している人"],
    googleMapsUrl: mapsUrl("横浜まぜそば 楽園 横浜駅"),
  },
];

export function getShopById(id: string): Shop | undefined {
  return SHOPS.find((shop) => shop.id === id);
}

export function getAllAreas(): string[] {
  return Array.from(new Set(SHOPS.map((shop) => shop.area)));
}

export function getAllGenres(): string[] {
  return Array.from(new Set(SHOPS.flatMap((shop) => shop.genres)));
}
